# Form implementation generated from reading ui file 'project_tab.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_ProjectTab(object):  # Renomeado para Ui_ProjectTab
    def setupUi(self, ProjectTab):
        ProjectTab.setObjectName("ProjectTab")
        ProjectTab.resize(400, 291)

        self.retranslateUi(ProjectTab)
        QtCore.QMetaObject.connectSlotsByName(ProjectTab)

    def retranslateUi(self, ProjectTab):
        _translate = QtCore.QCoreApplication.translate
        ProjectTab.setWindowTitle(_translate("ProjectTab", "Project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectTab = QtWidgets.QWidget()
    ui = Ui_ProjectTab()  # Atualizado aqui
    ui.setupUi(ProjectTab)
    ProjectTab.show()
    sys.exit(app.exec())

