# Form implementation generated from reading ui file 'train_tab.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_TrainTab(object):  # Renomeado para Ui_TrainTab
    def setupUi(self, WindowTrain):
        WindowTrain.setObjectName("WindowTrain")
        WindowTrain.resize(400, 300)
        
        self.pushButton = QtWidgets.QPushButton(parent=WindowTrain)
        self.pushButton.setGeometry(QtCore.QRect(40, 50, 93, 28))
        self.pushButton.setObjectName("pushButton")
        
        self.pushButton_2 = QtWidgets.QPushButton(parent=WindowTrain)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 50, 61, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.pushButton_3 = QtWidgets.QPushButton(parent=WindowTrain)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 100, 321, 151))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(WindowTrain)
        QtCore.QMetaObject.connectSlotsByName(WindowTrain)

    def retranslateUi(self, WindowTrain):
        _translate = QtCore.QCoreApplication.translate
        WindowTrain.setWindowTitle(_translate("WindowTrain", "Form"))
        self.pushButton.setText(_translate("WindowTrain", "train.csv"))
        self.pushButton_2.setText(_translate("WindowTrain", "load"))
        self.pushButton_3.setText(_translate("WindowTrain", "Terminal/info"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowTrain = QtWidgets.QWidget()
    ui = Ui_TrainTab()  # Atualizado aqui
    ui.setupUi(WindowTrain)
    WindowTrain.show()
    sys.exit(app.exec())
